language: c

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

sudo: false

env:
  - BUILD_TYPE=tiny
  - BUILD_TYPE=regular-asm

os:
  - linux
  # - osx

before_install:
  - git submodule update --init --recursive
  - git submodule update --recursive

script:
  - WITHOUT_AMALG=1 make ${BUILD_TYPE}
  - make test
